### ISSUE TITLE
[minor] convention for tags, v1.X.Y

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#28]
adding "v" is advised
https://semver.org/spec/v1.0.0.html#tagging-specification-semvertag

**Comment by KaiHabermann** [comment]
Can you rename tags?

**Comment by KaiHabermann** [comment]
It appears it would mess with the releases.
I would then make new releases in that form

**Comment by mmikhasenko** [comment]
Yes, fully agree

**Comment by KaiHabermann** [comment]
Ill leave this issue up till we have the next version
