### ISSUE TITLE
(minor) test name "test_4_body" -> `test_helicity_angles` 

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#33]
[The test](https://github.com/KaiHabermann/decayangle/blob/c703f9d4bc6bc229fb89e7a5e21975e5ed6475d1/tests/test_lorentz.py#L298-L310) validates computation of the helicity angles in tree different topologies for 3b decay, `L2pKpi`.

The name in the code is confusing. I've renamed the pull request, #32 , but a bit too late

**Comment by KaiHabermann** [comment]
Done
