### ISSUE TITLE
Numerical issues with 2pi: phi vs psi

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#34]
Here is a test of continuity: 
momenta orientation is obtained by rotating `Rz(phi)Ry(theta)Rz(psi)` of a fixed aligned kinematics. The `theta` is fixed, `phi`, and `psi` are x, and y.
 
Wigner azimuthal angle for relative `tree2` with respect to `tree1` is plotted

<img width="516" alt="image" src="https://github.com/KaiHabermann/decayangle/assets/22725744/62a82376-59e9-4a77-927b-6b204bebb78f">

the jumps are 2pi subtractions.

## What is the issue?

numerical fluctuation cause random distribution of the compensation phase +2pi between `phi` and `psi`.

## Practical checks

 - [x] check which angle gets 2pi addition in case of SU2 sign mismatch,
 - [ ] where exactly in computation the small-number computation happens, is it `atan(x,y)` or `acos`?

**Comment by mmikhasenko** [comment]
It's not an issue in the overall transformation, rather for the individual angle `psi` - it jumps together with `phi` changing from `-pi` to `pi`. The sum of the two is continuous

<img width="516" alt="image" src="https://github.com/KaiHabermann/decayangle/assets/22725744/c67452da-9179-4fec-a039-c713367b0f32">


```
result_psi = result_full[1].psi_rf
result_phi = result_full[1].phi_rf + np.pi
result = result_psi + result_phi
```

**Comment by KaiHabermann** [comment]
Ill look at this in more detail tomorrow. 
If you are at it right now, can you see, if this behaviour changes for different theta?
Or is it unrelated to theta?

**Comment by mmikhasenko** [comment]
Pattern is slightly different. I would say it is merely related to theta: since +- 2pi lives in the numerical precision domain, any fluctuation causes the jump, It can be phi, can be theta

**Comment by mmikhasenko** [comment]
Finally found the interesting stuff, that I was trying to do: the physical angle jump due to mismatch of domain of kinematic variables.

The helicity angles, (phi, theta),  (psi, ...) appear in all topologies. Every topology folds the SU(2) space (4pi x 2 x 4pi -> 2pi x 2 x 2pi) differently. Wigner rotations are responsible for matching the topologies on SU(2).

Below one sees the border of 2pi flip domains for wigner `psi_3(1)_for1`.

The local numerical jumps are destructing, therefore I plot `phi+psi`. It's not yet clear to me why I have to do `phi-psi` for the corner regions.

(phi-psi)
<img width="516" alt="image" src="https://github.com/KaiHabermann/decayangle/assets/22725744/ddf94300-6e08-4f17-93f3-15841feee58d">


(phi+psi)
<img width="516" alt="image" src="https://github.com/KaiHabermann/decayangle/assets/22725744/5325c588-211b-4131-a7d8-4c467fca733e">


Anyway, the effect that should be there is clearly visible.

**Comment by mmikhasenko** [comment]
Realized over the night that remaining jumps for `psi+phi` is the 4pi, it's not an issue, 4pi is true a ambiguity. Simply to remove by forsoing, [-pi, 3pi] range for the angles

**Comment by mmikhasenko** [comment]
@KaiHabermann added notes in the header of the issue.

**Comment by KaiHabermann** [comment]
I added an fmod by 4 pi to tthe image. Now it is smooth in both areas, but different. 
phi + psi
![test](https://github.com/KaiHabermann/decayangle/assets/60393298/c5867bc6-9526-4910-85b7-5ebf5f3e04de)
psi
![test_psi](https://github.com/KaiHabermann/decayangle/assets/60393298/f4b10625-503d-4341-aafd-b40bc7327310)
phi
![test_phi](https://github.com/KaiHabermann/decayangle/assets/60393298/586ea162-f633-4c52-a186-459d6c752da0)

**Comment by KaiHabermann** [comment]
@mmikhasenko should I show the above plot (the nice one) in the talk?

**Comment by mmikhasenko** [comment]
Yes, would be nice

**Comment by KaiHabermann** [comment]
![test_psi](https://github.com/KaiHabermann/decayangle/assets/60393298/78b0a05a-1b96-4d56-89ef-6b40e0413e07)
![test](https://github.com/KaiHabermann/decayangle/assets/60393298/53bd59c6-d2f9-4515-b883-2955213c8f1b)
![test_phi](https://github.com/KaiHabermann/decayangle/assets/60393298/2740e250-4ecb-4bf6-8eac-ebd66afd1221)

Final Version after the + 2 pi was moved to phi instead of psi. 
This removed the numerical instability for the 3body case (undetermined psi)

Closing this issue, as the latest release solves it

**Comment by KaiHabermann** [comment]
![test](https://github.com/KaiHabermann/decayangle/assets/60393298/f4c341dd-cb52-4beb-9633-9417d7770ebb)
![test_phi](https://github.com/KaiHabermann/decayangle/assets/60393298/ce94e932-e816-4cbd-a216-bad90bf40ce2)
![test_psi](https://github.com/KaiHabermann/decayangle/assets/60393298/603cd6de-76b9-482a-8cd4-3c062c434722)
