### ISSUE TITLE
[FR] `(phi,theta,-phi)` convention

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#45]
The convention on argument of Wigner D functions `D(phi, theta, 0)` is related to the transition between frames is done.
Normally we go between frames `B^{-1} R^{-1}`, where `R = Rz(phi) Ry(theta)`.

Extra `Rz(-phi)` added to both transformation gives extra phase to the helicity state, it does not change the value of the helicity.
But also, it impacts the Wigner rotations since all transformations get modified.

It's a curiosity question that I have since long:

- Are Wigner rotations simpler when using `(phi,theta,-phi)` conventions?

## Implementations:

Two new methods:
 - `helicity_angles_minus_phi_convention`
 - `wigner_rotations_minus_phi_convention`

## Test case

- (3b) Lc2pKpi, single spacial point, report values of the angles and Wigner rotations
- (4b) single spacial point, report values of the angles and Wigner rotations

## Reference

the convention is popular: mentioned in Martin-Spearman, "Elementary Particle Theory"
https://www.amazon.com/Elementary-particle-theory-Alan-Martin/dp/0720401577

Richman, An Experimenter's Guide to the Helicity Formalism
https://inspirehep.net/literature/202987

**Comment by KaiHabermann** [comment]
I would prefer convention flag.
Thus we can cover this case and the other FR with the existing interface

**Comment by mmikhasenko** [comment]
Can well be a flag, indeed!

Important to not mixing up conventions since the `angles` are closely linked to the `wigner_rotations`.

**Comment by KaiHabermann** [comment]
I would have all functions returning angles have a flag called `convention`. This will then get checked against the available ones.

**Comment by KaiHabermann** [comment]
Lets say we have three conventions: 
`"minus_phi", "canonical", "normal"`. What would be the best name for normal here?

**Comment by mmikhasenko** [comment]
![image](https://github.com/KaiHabermann/decayangle/assets/22725744/b433bc8a-85f4-4b93-8522-43b4867091f9)

![image](https://github.com/KaiHabermann/decayangle/assets/22725744/c6e50f4d-d336-4a60-bf79-81f0abdd8c26)

From Martin Spearman
Page 120
