### ISSUE TITLE
Debugging session for three formalisms

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#57]
We would like to demonstrate that three formalism give the same amplitude up to an overall phase.

Here are some thoughts how we can do it starting from 3b example.

Pick a general case of a fermionic decay, `1/2 -> 3/2, 1, 0`with a single resonance in all three channels.

```
A = A1 W1 + A2 W2 + A3 W3
```

where
- `A1` is a resonance of spin 2, (LS=2,1; ls=1,0),
- `A2` is a resonance of spin 3/2 (LS=1,3/2; ls=0,3/2),
- `A3` is a resonance of spin 5/2 (LS=2,5/2; ls=1,5/2),

1. pick a kinematic point (a reasonable set of 4 vectors)
2. start with the DPD as a reference.
3. build `helicity`, make sure it matches - will check if Wigner rotations are set correctly
4. test `minus_phi`
5. test `canonical`

what we look at the value of the unpolarized intensity, or also 2x4x3=24 values of the amplitudes.

**Comment by KaiHabermann** [comment]
All Done!
