### ISSUE TITLE
Incorrect output when running with julia

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#58]
In the example below, the angles `_23` are the angles onf the momentum p2+p3.
They are clearly (0,pi) since px = 0 and py=0, while the code returns `-0.92` for phi. 

<img width="731" alt="image" src="https://github.com/user-attachments/assets/e6bacbf6-8625-40ad-9af5-2921d354be29">

Attaching the notebook to a [public gist](https://gist.github.com/mmikhasenko/ee7c71ead37692f0cf4653e9c52171ea).

I do not exclude that the problem is on Julia site. We have to reproduce the notebook in clean python session.

**Comment by mmikhasenko** [comment]
Btw, you do not need to download it ever, just open the pluto and put 

https://gist.github.com/mmikhasenko/ee7c71ead37692f0cf4653e9c52171ea

to the address of the notebook

**Comment by mmikhasenko** [comment]
When both components are zero, the `phi` angle is pretty much undefined.

See the values below, these are the last digits of float that make the difference,

<img width="731" alt="image" src="https://github.com/user-attachments/assets/3dd80abe-a426-49f1-8834-2b0d1ed577ae">

It's fine in general. Importantly, the rotation is consistently propagated over the chain.

**Comment by mmikhasenko** [comment]
It's not worth the effort trying to fix it, we should just avoid 0, and pi when comparing.

Let's add a line in README and close the issue.

**Comment by KaiHabermann** [comment]
Yes I had the same thought.
Good that its cleared up though.

**Comment by KaiHabermann** [comment]
Maybe we could redefine it in such a way, that we rotate only theta and pick phi based on the direction of other momenta?

**Comment by mmikhasenko** [comment]
I think there is no other momentum that can be used

**Comment by KaiHabermann** [comment]
True. That Was my struggle back when I implemented this. It does not work well in rest frame :D
