### ISSUE TITLE
Compare Wigner Rotations with a sign

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#60]
We can replace the [long and complicated test](https://github.com/KaiHabermann/decayangle/blob/c66e1daaaa8adddea69afa3630ddbd6db48ec09a/tests/test_lorentz.py#L123) against DPD with a simple version that would check equally to the expected float value.

No random, no seed, let’s just fix the teat point.

Once you tell me the masses and sigmas, I print zetas with a correct sign.

**Comment by mmikhasenko** [comment]
## Setup
```
# invariants
σs = MandelstamTuple{Float64}((26.57159046, 17.86811729, 9.55283383))

# find masses
ms = let
	_ms = ThreeBodyMasses(1, 2, 3; m0=14)
	m0 = sqrt(sum(σs) - _ms.m1^2 - _ms.m2^2 - _ms.m3^2)
	ThreeBodyMasses(_ms.m1, _ms.m2, _ms.m3; m0)
end
# m0 = 6.32397
```

## print angles
```
"zeta_1(1)_for1" => 0.0
"zeta_2(1)_for1" => 0.19602946185017026
"zeta_3(1)_for1" => -0.47341288277954335
"zeta_1(2)_for1" => -0.19602946185017026
"zeta_2(2)_for1" => 0.0
"zeta_3(2)_for1" => -0.6694423446296955
"zeta_1(3)_for1" => 0.47341288277954335
"zeta_2(3)_for1" => 0.6694423446296955
"zeta_3(3)_for1" => 0.0
"zeta_1(1)_for2" => 0.0
"zeta_2(1)_for2" => 0.33838476527660183
"zeta_3(1)_for2" => 1.6547365635520592
"zeta_1(2)_for2" => -0.33838476527660183
"zeta_2(2)_for2" => 0.0
"zeta_3(2)_for2" => 1.3163517982754578
"zeta_1(3)_for2" => -1.6547365635520592
"zeta_2(3)_for2" => -1.3163517982754578
"zeta_3(3)_for2" => 0.0
"zeta_1(1)_for3" => 0.0
"zeta_2(1)_for3" => -0.6926241816619112
"zeta_3(1)_for3" => -0.30688282550974805
"zeta_1(2)_for3" => 0.6926241816619112
"zeta_2(2)_for3" => 0.0
"zeta_3(2)_for3" => 0.3857413561521633
"zeta_1(3)_for3" => 0.30688282550974805
"zeta_2(3)_for3" => -0.3857413561521633
"zeta_3(3)_for3" => 0.0
```

**Comment by KaiHabermann** [comment]
Can you explain the naming scheme again?
Just so we are sure

**Comment by KaiHabermann** [comment]
Figured it out. 
But it appears, that decayangle does not reporduce the dpd signs.
When we change from zeta_2(1)for1 to zeta_1(2)for1, we would expect a minus sign, but we get a 2pi flip in the phi angle.

**Comment by KaiHabermann** [comment]
This is sensible though, as we can not decode a negative value for theta. Thus I assume, this is the expected behavior.

**Comment by mmikhasenko** [comment]
ah you are right. You theta (as also mine) does not have the sign. I define the sign as `R(pi, theta, pi)`.
For you, it might be slightly different due not non-aligned kinematics.

I wonder if it is possible to run the `decayangle` on aligned kinematics. - overcome this `atan(0,0)` problem

**Comment by KaiHabermann** [comment]
Im not sure, if I have the atan problem right now...
I appear to see some kind of azimuthal difference in all cases, where I flip refrence.
Ill try to formulate it in a reliable way

**Comment by KaiHabermann** [comment]
```
0.19602946185017026 WignerAngles(phi_rf=array(9.42477796), theta_rf=array(0.19602279), psi_rf=array(-3.14159265))
-0.19602946185017026 WignerAngles(phi_rf=array(6.28318531), theta_rf=array(0.19602279), psi_rf=array(8.11068307e-16))
-0.47341288277954335 WignerAngles(phi_rf=array(3.14159265), theta_rf=array(0.47340421), psi_rf=array(-1.2246468e-16))
-0.6694423446296955 WignerAngles(phi_rf=array(9.42477796), theta_rf=array(0.669427), psi_rf=array(3.3986268e-16))
0.6694423446296955 WignerAngles(phi_rf=array(3.14159265), theta_rf=array(0.669427), psi_rf=array(2.01300436e-16))
```

This is what I get. Do you see a pattern?

**Comment by KaiHabermann** [comment]
The only thing I see is, that a minus will come with a 2 pi jump in phi - psi

**Comment by mmikhasenko** [comment]
the line

```
0.19602946185017026 WignerAngles(phi_rf=array(9.42477796), theta_rf=array(0.19602279), psi_rf=array(-3.14159265))
```

looks to me that we have the opposite sign, I read your transformation as `R(3pi, 0.196, -pi)`.
Could you please print the helicity angels for the chain `c` and the `ref` in this case? - I expect some unwanted 2pi there.

**Comment by mmikhasenko** [comment]
Do you have a matrix of the Lorentz transformation from 0->i, (inverse), for i->0 (Lambda)?

Let's define `L` is the i->0 transformation.
Then, 
```
R = L^-1 L_ref
```

**Comment by KaiHabermann** [comment]
I have that matrix internaly.
Internaly I use the passive definition (since we allways switch frame it is clearer).
Thus it is written as R =L L_ref^-1
I was trying to compare matrices, but failed ultimativ. 
We have to keep in mind, that particle ordering does effect the angles for decayangle, so there could be an issue aswell.

**Comment by KaiHabermann** [comment]
I misread you comment above though and tried agains 
Pi zeta -pi

**Comment by KaiHabermann** [comment]
Ill try the other definition later

**Comment by mmikhasenko** [comment]
Let's eliminate all uncertainties:

- ordering `off`.
- we compare the chain `((3,1),2)` with the reference chain `((2,3),1)`
- for particle 1

Let's use `L` for the paper Lorentz matrices, and `C` for the code matrices, `C = L^{-1}`.
Please confirm (make `x`),
- [ ] the chain matrix is built from 0 -> i along boosting,
- [ ] Multiplication order`C2 * C1 * C0`,
- [ ] the total matrix C is compared with the ref as `C*C_ref`

**Comment by KaiHabermann** [comment]
C * C_ref?
How can I understand that statement?
I thought its C _ C_ref^-1

**Comment by mmikhasenko** [comment]
ok, fixed!

**Comment by mmikhasenko** [comment]
just discussed on mattermost,

- suggest excluding, `^2_{k(2)}`, `^2_{2(k)}` from the testing leaving a comment that 
```
# The pi-difference wrt DPD is understood as compensation
# D*_{lam0, lam-lam2}(pi, theta, 0) * exp(i pi lam) 
#      = D*_{lam0, lam-lam2}(pi, theta, pi) * exp(i pi lam2)`
```
- for other angles I'd still assert if n_pi oddness is the same for phi, and psi.

**Comment by KaiHabermann** [comment]
Added test for this with #53
