### ISSUE TITLE
Inconsistency in definition of the particle-two rest-frame approach

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#62]
Currently, the particle-two rest frame is approach with `Rz(pi)Ry(pi)`.
The way to get the standard conventions (good parity relation), would be with using just `Rz(pi)`.

For the inverse (passive) transformations used in the code, 
```text
C(1) = Ry(-theta) * Rz(-phi)
C(2) = Ry(-pi)  * Ry(-theta) * Rz(-phi)
```

## Particle two convention

The consistent way to define the particle two, comes in when checking properties of helicity couplings.
```
| -p_z, j2,lam2> = (-1)^{j2-lam2} Rz(pi) Bz |0; j2, lam2>
```
the relation with parity is discussed in Martin-Spearman, and Richmann books.

## Reasoning with 3b example

The way to see, understand and check this algebra is to write down the definition of the helicity state for every decay chain.

Every helicity state can be written as `R*Bz |rest, lambda>` (acting on canonical).

Comparison of the `R*Bz` for different chains gives us the Wigner rotations.
So, I manually write down `i->0`transformation for every particle and every chain

```
Chain 1 ((2, 3), 1)
{((2, 3), 1): HelicityAngles(phi_rf=0.0, theta_rf=0.0),
(2, 3): HelicityAngles(phi_rf=0.0, theta_rf=2.2040260328305434)}

1: Rz(pi)
2: 0 rotation
3:  Rz(2.2) B Rz(pi)

Chain 2 ((3, 1), 2)
{((3, 1), 2): HelicityAngles(phi_rf=3.141592653589793, theta_rf=1.2888492044270379),
(3, 1): HelicityAngles(phi_rf=3.141592653589793, theta_rf=1.063056448747897)}

1: Ry(pi)*Rz(1.2)*Ry(pi)*Rz(1.06)*R(pi)  [ok]
2: Ry(pi)*Rz(1.2)*Rz(pi)                 [not ok] for good reason
3: Ry(pi)*Rz(1.2)*Ry(pi)*Rz(1.06)*R(pi)  [ok]


for the chain 2:
D_{lam0,lam-lam2}^{j0*}(pi, theta, 0) * D_{lam,lam2-lam1}^{j*}(pi, theta, 0)


Chain 3 ((1, 2), 3)
{((1, 2), 3): HelicityAngles(phi_rf=0.0, theta_rf=2.519541213603429),
(1, 2): HelicityAngles(phi_rf=0.0, theta_rf=1.1369115719521428)}

1: sub, 0 rotation
2: sub, Rz(1.13)*Rz(pi) rotation
3: 0, Rz(2.5)*Rz(pi) rotation
```

**Comment by mmikhasenko** [comment]
Btw,

I think the reason of the original, inconsistent transformation is from a common way of computing solid angle of the particle in `-vec p` direction, which is `pi+phi, pi-theta`. One has to be careful with such things.

**Comment by KaiHabermann** [comment]
added with #53
