### ISSUE TITLE
Cross check of formalisms. Chain1 as ref

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#64]
Here we agree on setup to proceed with matching of all formalisms

## Kinematics

Let's consider a reaction with quantum numbers, labeled as 0 -> 1,2,3

- masses: `6.32397 -> 1.0, 2.0, 3.0`
- spins: `1/2 -> 1/2, 1, 0`
- chains:
   - chain `(12)3`: j=1/2, with `ls=(1,1/2)`, and `LS=(1, 3/2)`
   - chain `(23)1`: j=2, with `ls=(2,1)`, and `LS=(1, 3/2)`

## The test point

- orientation angles `(phi_rf, cos_theta_rf, psi_rf) = (0.3, 0.4, 0.5)`. The value polar angle is determined through the `cos` function. 
- Dalitz point is specified as `m23sq`, `m31sq`, `m12sq`, respectively,
```julia
σs = ((26.57159046, 17.86811729, 9.55283383))
```
- spins projections, let's say `lam0=-1/2` `lam1= 1/2`, `lam2=1`, and `lam3=0`

## Amplitude
computed as `A_{c=1} + A_{c=3} * W_{3(1)}`, with the first term in the sum being called `term1`, and the second term with a summation over Wigner rotation indices is being referred to as the `term2`.

Values yielded by the formalisms printed for two terms separately:

#### helicity

```txt
term1: -0.540354116266746-0.02084320694159516j
term2: -0.49899891547281655+0.030820810874496913j
```
vs dpd with phase

```txt
term1 = -0.5403548264386938 - 0.02084602118881694im
intensity_1 = 1.01
term2 = -0.4990042280839077 + 0.030819880379902173im
```

- [x] **matched**

#### minus_phi

```
term1: -0.44278118293224566+0.31042202609213687j
term2: -0.37859261634645197+0.32652330831650717j
```

vs DPD with the phase

```
term1 = -0.4427834514327887 + 0.31042021550192717im
term2 = -0.378597408752749 + 0.3265257826848471im
```

- [x] **matched**

**Comment by mmikhasenko** [comment]
Aligned amplitude agrees for all components (helicity vs dpd)

![image](https://github.com/user-attachments/assets/4e63f5e0-b5ab-42d7-b934-fee8915801a5)

**Comment by mmikhasenko** [comment]
In case we want to update the numbers of DPD for the LS=(4,3)

```julia
# helicity
term1 = -0.1431449368175614 + 0.12414690695134413im
term2 = -0.4990042280839077 + 0.030819880379902184im

#minus phi
term1=-0.03882334464365838 + 0.1854607110758747im
term2=-0.378597408752749 + 0.3265257826848471im
```

**Comment by KaiHabermann** [comment]
For `decayangle` implementation we get


```
  Helicity
Term 1 (-0.14315554700441074+0.12414558894503328j) Intensity 1.0126272647367502
Term 2 (-0.49899891547281655+0.030820810874496916j) Intensity 1.0000000000000004
Intensity 2.183806535188113
Minus Phi
Term 1 (-0.03883258888101088+0.1854660829732478j) Intensity 1.0126272647367505
Term 2 (-0.37859261634645197+0.32652330831650717j) Intensity 1.0000000000000002
Intensity 2.183806535188113
```
